version: '3.8'

services:
  car-scraper-api:
    build: .
    container_name: car-scraper-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
      - MAX_CONCURRENT_JOBS=5
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    mem_limit: 2g
    cpus: '2.0'

  # Opcional: Redis para storage de jobs
  redis:
    image: redis:7-alpine
    container_name: scraper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
